In [2]:
A=[1,2,1;3,2,1;2,2,1]
B=[1,1,2;2,1,1;3,3,1]

#transpose of A = A'
A'*B

A*B

A =

   1   2   1
   3   2   1
   2   2   1

B =

   1   1   2
   2   1   1
   3   3   1

ans =

   13   10    7
   12   10    8
    6    5    4

ans =

    8    6    5
   10    8    9
    9    7    7



In [13]:
svd(A)
[u,s,v] = svd(A)

det(A)

det(s)

ans =

  5.2845e+000
  1.0365e+000
  1.0091e-018

u =

  -0.43602   0.80201  -0.40825
  -0.69860  -0.58761  -0.40825
  -0.56731   0.10720   0.81650

s =

Diagonal Matrix

  5.2845e+000            0            0
            0  1.0365e+000            0
            0            0  1.0091e-018

v =

  -0.69381  -0.72015   0.00000
  -0.64412   0.62057  -0.44721
  -0.32206   0.31028   0.89443

ans = 0
ans =   5.5270e-018


In [16]:
svd(B)
[u,s,v] = svd(B)

unique(svd(B))

length(unique(svd(B)))

det(B)

det(s)

ans =

   5.32815
   1.48758
   0.63083

u =

  -0.387844  -0.875622  -0.287859
  -0.446717  -0.094607   0.889659
  -0.806239   0.473640  -0.354462

s =

Diagonal Matrix

   5.32815         0         0
         0   1.48758         0
         0         0   0.63083

v =

  -0.694424   0.239372   0.678584
  -0.610583   0.302970  -0.731709
  -0.380741  -0.922448  -0.064233

ans =

   0.63083
   1.48758
   5.32815

ans =  3
ans =  5.0000
ans =  5.0000


In [4]:
eig(A)
A^-1
eig(B)
B^-1

ans =

  5.0000e+000
  -1.0000e+000
  1.1928e-017

ans =

   Inf   Inf   Inf
   Inf   Inf   Inf
   Inf   Inf   Inf

ans =

   4.85844 + 0.00000i
  -0.92922 + 0.40704i
  -0.92922 - 0.40704i

ans =

  -4.0000e-001  1.0000e+000  -2.0000e-001
  2.0000e-001  -1.0000e+000  6.0000e-001
  6.0000e-001  3.3307e-017  -2.0000e-001



In [5]:
qr(A)
qr(B)

ans =

  -3.7417e+000  -3.2071e+000  -1.6036e+000
  8.0178e-001  1.3093e+000  6.5465e-001
  5.3452e-001  1.4995e-001  -1.5938e-017

ans =

  -3.7417e+000  -3.2071e+000  -1.8708e+000
  5.3452e-001  8.4515e-001  -6.6613e-016
  8.0178e-001  -4.0015e-001  -1.5811e+000



In [7]:
det(A)

det(B)

ans = 0
ans =  5.0000


In [8]:
eig(A)

eig(B)

ans =

  5.0000e+000
  -1.0000e+000
  1.1928e-017

ans =

   4.85844 + 0.00000i
  -0.92922 + 0.40704i
  -0.92922 - 0.40704i



In [18]:
rank(A)
inv(A)
A^-1

rank(B)
inv(B)
B^-1

ans =  2
ans =

   Inf   Inf   Inf
   Inf   Inf   Inf
   Inf   Inf   Inf

ans =

   Inf   Inf   Inf
   Inf   Inf   Inf
   Inf   Inf   Inf

ans =  3
ans =

  -4.0000e-001  1.0000e+000  -2.0000e-001
  2.0000e-001  -1.0000e+000  6.0000e-001
  6.0000e-001  3.3307e-017  -2.0000e-001

ans =

  -4.0000e-001  1.0000e+000  -2.0000e-001
  2.0000e-001  -1.0000e+000  6.0000e-001
  6.0000e-001  3.3307e-017  -2.0000e-001



m =  3
n =  3
Q =

   0   0   0
   0   0   0
   0   0   0

R =

   0   0   0
   0   0   0
   0   0   0

v =

   1
   3
   2

R =

   3.74166   0.00000   0.00000
   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000

Q =

   0.26726   0.00000   0.00000
   0.80178   0.00000   0.00000
   0.53452   0.00000   0.00000

v =

   2
   2
   2

R =

   3.74166   3.74166   0.00000
   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000

v =

  1.0000e+000
  -1.0000e+000
  -4.4409e-016

R =

   3.74166   3.74166   0.00000
   0.00000   1.41421   0.00000
   0.00000   0.00000   0.00000

Q =

   0.26726   0.70711   0.00000
   0.80178  -0.70711   0.00000
   0.53452  -0.00000   0.00000

v =

   1
   1
   1

R =

   3.74166   3.74166   3.74166
   0.00000   1.41421   0.00000
   0.00000   0.00000   0.00000

v =

  -2.2204e-016
  -2.0000e+000
  -1.0000e+000

R =

   3.74166   3.74166   3.74166
   0.00000   1.41421  -0.00000
   0.00000   0.00000   0.00000

v =

  8.5008e-016
  -2.0000e+000
  -1.

In [40]:
X = [1,0;0,1;1,0]

[q,r] = qr(X)

qr(X)

[Q,R] = qr(A)

X =

   1   0
   0   1
   1   0

q =

  -0.70711   0.00000  -0.70711
  -0.00000   1.00000   0.00000
  -0.70711  -0.00000   0.70711

r =

  -1.41421   0.00000
   0.00000   1.00000
   0.00000   0.00000

ans =

  -1.41421   0.00000
   0.00000   1.00000
   0.70711   0.00000

Q =

  -0.26726   0.87287  -0.40825
  -0.80178  -0.43644  -0.40825
  -0.53452   0.21822   0.81650

R =

  -3.74166  -3.20713  -1.60357
   0.00000   1.30931   0.65465
   0.00000   0.00000  -0.00000



In [39]:
#classical gram-schmidt
function [Q,R] = gs(A)
    [m,n] = size(A)

    Q = zeros(m,n)
    R = zeros(n,n)

    for j = 1:n
        v = A(:,j)
        for i = 1:j-1
            R(i,j)=Q(:,i)'*A(:,i)
            v=v-R(i,j)*Q(:,i)
        endfor
        R(j,j)=norm((v),2)
        Q(:,j)=v/R(j,j)
    endfor
end
################################
#                              #
################################

#modified gram-schmidt
function [Q,R] = mgs(A)
    [m,n] = size(A)

    Q = zeros(m,n)
    R = zeros(n,n)
    v = zeros(m,n)

    for i = 1:n
        v(:,i) = A(:,i)
    endfor 
    for i = 1:n
        R(i,i) = norm(v(:,i),2)
        Q(:,i) = v(:,i)/R(i,i)
        for j = i+1:n
            R(i,j)=Q(:,i)'*v(:,j)
            v(:,j)=v(:,j)-R(i,j)*Q(:,i)
        endfor
    endfor
end

gs(A)

mgs(A)

m =  3
n =  3
Q =

   0   0   0
   0   0   0
   0   0   0

R =

   0   0   0
   0   0   0
   0   0   0

v =

   1
   3
   2

R =

   3.74166   0.00000   0.00000
   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000

Q =

   0.26726   0.00000   0.00000
   0.80178   0.00000   0.00000
   0.53452   0.00000   0.00000

v =

   2
   2
   2

R =

   3.74166   3.74166   0.00000
   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000

v =

  1.0000e+000
  -1.0000e+000
  -4.4409e-016

R =

   3.74166   3.74166   0.00000
   0.00000   1.41421   0.00000
   0.00000   0.00000   0.00000

Q =

   0.26726   0.70711   0.00000
   0.80178  -0.70711   0.00000
   0.53452  -0.00000   0.00000

v =

   1
   1
   1

R =

   3.74166   3.74166   3.74166
   0.00000   1.41421   0.00000
   0.00000   0.00000   0.00000

v =

  -2.2204e-016
  -2.0000e+000
  -1.0000e+000

R =

   3.74166   3.74166   3.74166
   0.00000   1.41421  -0.00000
   0.00000   0.00000   0.00000

v =

  8.5008e-016
  -2.0000e+000
  -1.

In [45]:
X = [1,2,1;-2,-3,1;3,5,0]

rank(X)

[u,s,v] = svd(X)


X =

   1   2   1
  -2  -3   1
   3   5   0

ans =  2
u =

  -0.30519  -0.75731  -0.57735
   0.50326  -0.64296   0.57735
  -0.80845  -0.11435   0.57735

s =

Diagonal Matrix

  7.2097e+000            0            0
            0  1.4213e+000            0
            0            0  8.8918e-018

v =

  -0.518336   0.130546   0.845154
  -0.854736  -0.110833  -0.507093
   0.027472  -0.985228   0.169031

